on: [push, pull_request]

jobs:
  armv7l:
    runs-on: ubuntu-18.04
    name: Build on ARMv7l
    steps:
      - uses: actions/checkout@v2
      - uses: uraimo/run-on-arch-action@v1.0.9
        id: runcmd
        with:
          architecture: armv7
          distribution: buster
          run: |
            uname -a
            echo ::set-output name=uname::$(uname -a)
      - name: Get the output
        run: |
            echo "The uname output was ${{ steps.runcmd.outputs.uname }}"
